---
apiVersion: v1
kind: Service
metadata:
 name: code-server
spec:
 ports:
 - port: 8080
   targetPort: 8080
   name: http
 selector:
   app: code-server
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: passwd
data: 
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
    bin:x:2:2:bin:/bin:/usr/sbin/nologin
    sys:x:3:3:sys:/dev:/usr/sbin/nologin
    sync:x:4:65534:sync:/bin:/bin/sync
    games:x:5:60:games:/usr/games:/usr/sbin/nologin
    man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
    lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
    mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
    news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
    uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
    proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
    www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
    backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
    list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
    irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
    gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
    nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
    _apt:x:100:65534::/nonexistent:/usr/sbin/nologin
    ${USERNAME}:x:${UID}:${GID}::${HOMEDIR}:/bin/bash


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: coact-dev.slac.stanford.edu
    http:
      paths:
      - path: /code-server(/?|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      securityContext:
        runAsUser: 7017
        runAsGroup: 1051
        fsGroup: 1051
      initContainers:
      - name: init
        image: bhgedigital/envsubst
        command:
        - sh
        - -c
        - envsubst < /in/passwd > /out/passwd 
        env:
        - name: USERNAME
          value: ytl
        - name: UID
          value: "7017"
        - name: GID
          value: "1051"
        - name: HOMEDIR
          value: /sdf/home/y/ytl
        volumeMounts:
        - name: init
          mountPath: /out
        - name: init-passwd
          mountPath: /in/passwd
          subPath: passwd
      containers:
      - image: linuxserver/code-server
        name: code-server
        command:
        - /app/code-server/lib/node 
        - /app/code-server 
        - --bind-addr 
        - 0.0.0.0:8443 
        - --user-data-dir 
        - /config/.local/share/code-server/data 
        - --extensions-dir 
        - /config/.local/share/code-server/extensions 
        - --disable-telemetry 
        - --auth 
        - password
        - /sdf/home/y/ytl/
        env:
        - name: PASSWORD
          value: "letmein"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: '5'
        volumeMounts: 
        - name: init
          mountPath: /etc/passwd
          subPath: passwd
        # - name: terminfo
        #   mountPath: /usr/share/terminfo
        - name: sdf-home
          mountPath: /config
          subPath: y/ytl/
        - name: sdf-home
          mountPath: /sdf/home
        # - name: coact-ui-code
        #   mountPath: /workspace/coact-ui/
        # - name: coact-api-code
        #   mountPath: /workspace/coact-api/
      volumes:
      - name: sdf-home
        persistentVolumeClaim:
          claimName: sdf-home
      - name: init
        emptyDir: {}
      - name: init-passwd
        configMap:
          name: passwd
          items:
          - key: passwd
            path: passwd
      # - name: coact-ui-code
      #   persistentVolumeClaim:
      #     claimName: coact-ui-code
      # - name: coact-api-code
      #   persistentVolumeClaim:
      #     claimName: coact-api-code
      # - name: terminfo
      #   hostPath:
      #     path: /usr/share/terminfo
      #     type: Directory

